export interface Verse {
  text: string;
  reference: string;
  theme: string;
}

export const verses: Verse[] = [
  // 1-50 : Foi et Confiance
  { text: "Je puis tout par celui qui me fortifie.", reference: "Philippiens 4:13", theme: "Foi" },
  { text: "Or, la foi est une ferme assurance des choses qu'on espère, une démonstration de celles qu'on ne voit pas.", reference: "Hébreux 11:1", theme: "Foi" },
  { text: "Confie-toi en l'Éternel de tout ton cœur, et ne t'appuie pas sur ta sagesse.", reference: "Proverbes 3:5", theme: "Foi" },
  { text: "Jésus lui dit : Si tu peux !... Tout est possible à celui qui croit.", reference: "Marc 9:23", theme: "Foi" },
  { text: "Le juste vivra par sa foi.", reference: "Romains 1:17", theme: "Foi" },
  { text: "Recommande ton sort à l'Éternel, mets en lui ta confiance, et il agira.", reference: "Psaumes 37:5", theme: "Foi" },
  { text: "Ne t'ai-je pas donné cet ordre : Fortifie-toi et prends courage ? Ne t'effraye point et ne t'épouvante point, car l'Éternel, ton Dieu, est avec toi dans tout ce que tu entreprendras.", reference: "Josué 1:9", theme: "Foi" },
  { text: "Et mon Dieu pourvoira à tous vos besoins selon sa richesse, avec gloire, en Jésus-Christ.", reference: "Philippiens 4:19", theme: "Foi" },
  { text: "Quand je marche dans la vallée de l'ombre de la mort, je ne crains aucun mal, car tu es avec moi.", reference: "Psaumes 23:4", theme: "Foi" },
  { text: "Voici, Dieu est ma délivrance, je serai plein de confiance, et je ne craindrai rien.", reference: "Ésaïe 12:2", theme: "Foi" },
  { text: "Le Seigneur est mon secours, je ne craindrai rien ; que peut me faire un homme ?", reference: "Hébreux 13:6", theme: "Foi" },
  { text: "C'est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c'est le don de Dieu.", reference: "Éphésiens 2:8", theme: "Foi" },
  { text: "Car nous marchons par la foi et non par la vue.", reference: "2 Corinthiens 5:7", theme: "Foi" },
  { text: "Ceux qui se confient en l'Éternel sont comme la montagne de Sion : elle ne chancelle point, elle est affermie pour toujours.", reference: "Psaumes 125:1", theme: "Foi" },
  { text: "Ma bouche publiera ta justice, ton salut chaque jour, car j'en ignore le nombre.", reference: "Psaumes 71:15", theme: "Foi" },
  { text: "La foi vient de ce qu'on entend, et ce qu'on entend vient de la parole de Christ.", reference: "Romains 10:17", theme: "Foi" },
  { text: "Que tout ce que vous faites se fasse avec amour.", reference: "1 Corinthiens 16:14", theme: "Foi" },
  { text: "Je cherche l'Éternel, et il me répond ; il me délivre de toutes mes frayeurs.", reference: "Psaumes 34:5", theme: "Foi" },
  { text: "Si Dieu est pour nous, qui sera contre nous ?", reference: "Romains 8:31", theme: "Foi" },
  { text: "Le bouclier de la foi vous permettra d'éteindre tous les traits enflammés du malin.", reference: "Éphésiens 6:16", theme: "Foi" },
  { text: "Le nom de l'Éternel est une tour forte ; le juste s'y réfugie, et se trouve en sûreté.", reference: "Proverbes 18:10", theme: "Foi" },
  { text: "Tu gardes dans une paix parfaite l'esprit qui est ferme, car il se confie en toi.", reference: "Ésaïe 26:3", theme: "Foi" },
  { text: "Car rien n'est impossible à Dieu.", reference: "Luc 1:37", theme: "Foi" },
  { text: "Mais celui qui doute est condamné s'il mange, parce qu'il n'agit pas par conviction ; tout ce qui n'est pas le produit d'une conviction est péché.", reference: "Romains 14:23", theme: "Foi" },
  { text: "Crois au Seigneur Jésus, et tu seras sauvé, toi et ta famille.", reference: "Actes 16:31", theme: "Foi" },
  { text: "Si vous aviez de la foi comme un grain de sénevé, vous diriez à ce sycomore : Déracine-toi, et plante-toi dans la mer ; et il vous obéirait.", reference: "Luc 17:6", theme: "Foi" },
  { text: "C'est en toute tranquillité et confiance que sera votre force.", reference: "Ésaïe 30:15", theme: "Foi" },
  { text: "Celui qui croit en moi, des fleuves d'eau vive couleront de son sein, comme dit l'Écriture.", reference: "Jean 7:38", theme: "Foi" },
  { text: "Je t'exalterai, ô mon Dieu, mon roi ! Et je bénirai ton nom toujours et à perpétuité.", reference: "Psaumes 145:1", theme: "Foi" },
  { text: "Le juste est comme un jeune lion plein d'assurance.", reference: "Proverbes 28:1", theme: "Foi" },
  { text: "Heureux l'homme qui place en l'Éternel sa confiance.", reference: "Psaumes 40:5", theme: "Foi" },
  { text: "La Parole de l'Éternel est droite, et toutes ses œuvres s'accomplissent avec fidélité.", reference: "Psaumes 33:4", theme: "Foi" },
  { text: "Par sa connaissance mon serviteur juste justifiera beaucoup d'hommes.", reference: "Ésaïe 53:11", theme: "Foi" },
  { text: "Car la promesse est pour vous, pour vos enfants, et pour tous ceux qui sont au loin.", reference: "Actes 2:39", theme: "Foi" },
  { text: "Ne crains rien, car je te rachète, je t'appelle par ton nom : tu es à moi !", reference: "Ésaïe 43:1", theme: "Foi" },
  { text: "Le Seigneur soutient tous ceux qui tombent, et il redresse tous ceux qui sont courbés.", reference: "Psaumes 145:14", theme: "Foi" },
  { text: "L'Éternel est ma force et mon bouclier ; en lui mon cœur se confie, et je suis secouru.", reference: "Psaumes 28:7", theme: "Foi" },
  { text: "Heureux ceux qui n'ont pas vu, et qui ont cru !", reference: "Jean 20:29", theme: "Foi" },
  { text: "Et voici la victoire qui triomphe du monde : notre foi.", reference: "1 Jean 5:4", theme: "Foi" },
  { text: "Dieu n'est point un homme pour mentir, ni fils d'un homme pour se repentir. Ce qu'il a dit, ne le fera-t-il pas ?", reference: "Nombres 23:19", theme: "Foi" },
  { text: "C'est en toi, Éternel, que je cherche un refuge : que je ne sois jamais confondu !", reference: "Psaumes 31:2", theme: "Foi" },
  { text: "Que le Christ habite dans vos cœurs par la foi.", reference: "Éphésiens 3:17", theme: "Foi" },
  { text: "Je sais en qui j'ai cru, et je suis persuadé qu'il a la puissance de garder mon dépôt jusqu'à ce jour-là.", reference: "2 Timothée 1:12", theme: "Foi" },
  { text: "Ceux qui sèment avec larmes moissonneront avec chants de triomphe.", reference: "Psaumes 126:5", theme: "Foi" },
  { text: "Car quiconque demande reçoit, celui qui cherche trouve, et l'on ouvre à celui qui frappe.", reference: "Matthieu 7:8", theme: "Foi" },
  { text: "Dieu est pour nous un refuge et un appui, un secours qui ne manque jamais dans la détresse.", reference: "Psaumes 46:2", theme: "Foi" },
  { text: "Je leverai mes yeux vers les montagnes... D'où me viendra le secours ? Le secours me vient de l'Éternel.", reference: "Psaumes 121:1-2", theme: "Foi" },
  { text: "L'Éternel est mon berger : je ne manquerai de rien.", reference: "Psaumes 23:1", theme: "Foi" },
  { text: "Éternel ! ma force, mon rocher, ma forteresse, mon libérateur !", reference: "Psaumes 18:2", theme: "Foi" },
  { text: "Ne vous inquiétez de rien ; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications.", reference: "Philippiens 4:6", theme: "Foi" },

  // 51-100 : Paix et Réconfort
  { text: "Je vous laisse la paix, je vous donne ma paix. Je ne vous donne pas comme le monde donne.", reference: "Jean 14:27", theme: "Paix" },
  { text: "Que la paix de Christ, à laquelle vous avez été appelés pour former un seul corps, règne dans vos cœurs.", reference: "Colossiens 3:15", theme: "Paix" },
  { text: "Et la paix de Dieu, qui surpasse toute intelligence, gardera vos cœurs et vos pensées en Jésus-Christ.", reference: "Philippiens 4:7", theme: "Paix" },
  { text: "L'Éternel donnera de la force à son peuple ; l'Éternel bénira son peuple en lui donnant la paix.", reference: "Psaumes 29:11", theme: "Paix" },
  { text: "Je me couche et je m'endors en paix, car toi seul, ô Éternel ! tu me donnes la sécurité dans ma demeure.", reference: "Psaumes 4:9", theme: "Paix" },
  { text: "Heureux ceux qui procurent la paix, car ils seront appelés fils de Dieu !", reference: "Matthieu 5:9", theme: "Paix" },
  { text: "Recherche la paix et poursuis-la.", reference: "Psaumes 34:15", theme: "Paix" },
  { text: "Le châtiment qui nous donne la paix est tombé sur lui, et c'est par ses meurtrissures que nous sommes guéris.", reference: "Ésaïe 53:5", theme: "Paix" },
  { text: "Le fruit de la justice est semé dans la paix par ceux qui recherchent la paix.", reference: "Jacques 3:18", theme: "Paix" },
  { text: "Que le Seigneur de la paix vous donne lui-même la paix en tout temps, de toute manière !", reference: "2 Thessaloniciens 3:16", theme: "Paix" },
  { text: "Il y a beaucoup de paix pour ceux qui aiment ta loi, et il ne leur arrive aucun malheur.", reference: "Psaumes 119:165", theme: "Paix" },
  { text: "Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.", reference: "Matthieu 11:28", theme: "Paix" },
  { text: "Trouvez en moi votre repos. Vous aurez des tribulations dans le monde ; mais prenez courage, j'ai vaincu le monde.", reference: "Jean 16:33", theme: "Paix" },
  { text: "L'Éternel combattra pour vous ; et vous, gardez le silence.", reference: "Exode 14:14", theme: "Paix" },
  { text: "Quand les voies d'un homme sont agréables à l'Éternel, il réconcilie avec lui même ses ennemis.", reference: "Proverbes 16:7", theme: "Paix" },
  { text: "S'il est possible, autant que cela dépend de vous, soyez en paix avec tous les hommes.", reference: "Romains 12:18", theme: "Paix" },
  { text: "Le Dieu de paix écrasera bientôt Satan sous vos pieds.", reference: "Romains 16:20", theme: "Paix" },
  { text: "Car Dieu n'est pas un Dieu de désordre, mais de paix.", reference: "1 Corinthiens 14:33", theme: "Paix" },
  { text: "De plus, l'affection de l'esprit, c'est la vie et la paix.", reference: "Romains 8:6", theme: "Paix" },
  { text: "L'œuvre de la justice sera la paix, et le fruit de la justice le repos et la sécurité pour toujours.", reference: "Ésaïe 32:17", theme: "Paix" },
  { text: "Béni soit le Dieu et Père de notre Seigneur Jésus-Christ, le Père des miséricordes et le Dieu de tout réconfort !", reference: "2 Corinthiens 1:3", theme: "Paix" },
  { text: "Il réconforte les humbles.", reference: "2 Corinthiens 7:6", theme: "Paix" },
  { text: "Déchargez-vous sur lui de tous vos soucis, car lui-même prend soin de vous.", reference: "1 Pierre 5:7", theme: "Paix" },
  { text: "Quand les pensées se bousculent en foule au-dedans de moi, tes consolations réjouissent mon âme.", reference: "Psaumes 94:19", theme: "Paix" },
  { text: "Consolez, consolez mon peuple, dit votre Dieu.", reference: "Ésaïe 40:1", theme: "Paix" },
  { text: "Comme un homme que sa mère console, ainsi je vous consolerai.", reference: "Ésaïe 66:13", theme: "Paix" },
  { text: "Car l'Éternel console son peuple, il a pitié de ses malheureux.", reference: "Ésaïe 49:13", theme: "Paix" },
  { text: "Heureux les affligés, car ils seront consolés !", reference: "Matthieu 5:4", theme: "Paix" },
  { text: "Il essuiera toute larme de leurs yeux, et la mort ne sera plus ; il n'y aura plus ni deuil, ni cri, ni douleur.", reference: "Revelation 21:4", theme: "Paix" },
  { text: "Je t'ai aimé d'un amour éternel ; c'est pourquoi je te conserve ma bonté.", reference: "Jérémie 31:3", theme: "Paix" },
  { text: "Le Dieu d'espérance vous remplisse de toute joie et de toute paix dans la foi.", reference: "Romains 15:13", theme: "Paix" },
  { text: "Ne crains rien, car je suis avec toi ; ne promène pas des regards inquiets, car je suis ton Dieu.", reference: "Ésaïe 41:10", theme: "Paix" },
  { text: "L'Éternel est près de ceux qui ont le cœur brisé, et il sauve ceux qui ont l'esprit dans l'abattement.", reference: "Psaumes 34:19", theme: "Paix" },
  { text: "Quand je dis : Mon pied chancelle ! Ta bonté, ô Éternel ! me sert d'appui.", reference: "Psaumes 94:18", theme: "Paix" },
  { text: "Il guérit ceux qui ont le cœur brisé, et il panse leurs blessures.", reference: "Psaumes 147:3", theme: "Paix" },
  { text: "Mon âme, bénis l'Éternel, et n'oublie aucun de ses bienfaits !", reference: "Psaumes 103:2", theme: "Paix" },
  { text: "L'Éternel est miséricordieux et compatissant, lent à la colère et riche en bonté.", reference: "Psaumes 103:8", theme: "Paix" },
  { text: "Comme un père a compassion de ses enfants, l'Éternel a compassion de ceux qui le craignent.", reference: "Psaumes 103:13", theme: "Paix" },
  { text: "Mais la bonté de l'Éternel dure à jamais pour ceux qui le craignent.", reference: "Psaumes 103:17", theme: "Paix" },
  { text: "Sous ses ailes tu trouveras un refuge ; sa fidélité est un bouclier et une cuirasse.", reference: "Psaumes 91:4", theme: "Paix" },
  { text: "Aucun malheur ne t'arrivera, aucun fléau n'approchera de ta tente.", reference: "Psaumes 91:10", theme: "Paix" },
  { text: "Car il ordonnera à ses anges de te garder dans toutes tes voies.", reference: "Psaumes 91:11", theme: "Paix" },
  { text: "Parce qu'il m'aime, je le délivrerai ; je le protégerai, puisqu'il connaît mon nom.", reference: "Psaumes 91:14", theme: "Paix" },
  { text: "Il m'invoquera, et je lui répondrai ; je serai avec lui dans la détresse.", reference: "Psaumes 91:15", theme: "Paix" },
  { text: "Le Dieu de paix soit avec vous tous ! Amen !", reference: "Romains 15:33", theme: "Paix" },
  { text: "Recherchez le bien de la ville... et priez l'Éternel en sa faveur, parce que votre paix dépend de la sienne.", reference: "Jérémie 29:7", theme: "Paix" },
  { text: "Que le Seigneur dirige vos cœurs vers l'amour de Dieu et vers la patience de Christ !", reference: "2 Thessaloniciens 3:5", theme: "Paix" },
  { text: "La paix soit avec vous ! Jésus se présenta au milieu d'eux.", reference: "Jean 20:19", theme: "Paix" },
  { text: "Priez sans cesse. Rendez grâces en toutes choses.", reference: "1 Thessaloniciens 5:17-18", theme: "Paix" },
  { text: "Mon cœur est affermi, ô Dieu ! mon cœur est affermi.", reference: "Psaumes 57:8", theme: "Paix" },

  // 101-150 : Joie et Allégresse
  { text: "La joie de l'Éternel sera votre force.", reference: "Néhémie 8:10", theme: "Joie" },
  { text: "Réjouissez-vous toujours dans le Seigneur ; je le répète, réjouissez-vous.", reference: "Philippiens 4:4", theme: "Joie" },
  { text: "Tu me feras connaître le sentier de la vie ; il y a d'abondantes joies devant ta face.", reference: "Psaumes 16:11", theme: "Joie" },
  { text: "Le cœur joyeux rend le visage serein, mais quand le cœur est triste, l'esprit est abattu.", reference: "Proverbes 15:13", theme: "Joie" },
  { text: "Jusqu'à présent vous n'avez rien demandé en mon nom. Demandez, et vous recevrez, afin que votre joie soit parfaite.", reference: "Jean 16:24", theme: "Joie" },
  { text: "Servez l'Éternel avec joie, venez avec allégresse en sa présence !", reference: "Psaumes 100:2", theme: "Joie" },
  { text: "Le fruit de l'Esprit, c'est l'amour, la joie, la paix, la patience, la bonté, la bienveillance, la foi.", reference: "Galates 5:22", theme: "Joie" },
  { text: "Vous sortirez avec joie, et vous serez conduits en paix ; les montagnes et les collines éclateront en cris de joie devant vous.", reference: "Ésaïe 55:12", theme: "Joie" },
  { text: "Mon cœur se réjouit en l'Éternel, ma force a été relevée par l'Éternel.", reference: "1 Samuel 2:1", theme: "Joie" },
  { text: "Tu as changé mon deuil en allégresse, tu as délié mon sac, et tu m'as ceint de joie.", reference: "Psaumes 30:12", theme: "Joie" },
  { text: "C'est ici la journée que l'Éternel a faite : Qu'elle soit pour nous un sujet d'allégresse et de joie !", reference: "Psaumes 118:24", theme: "Joie" },
  { text: "Mon âme se réjouira en l'Éternel, elle s'égayera de son salut.", reference: "Psaumes 35:9", theme: "Joie" },
  { text: "Les préceptes de l'Éternel sont droits, ils réjouissent le cœur.", reference: "Psaumes 19:9", theme: "Joie" },
  { text: "Bien qu'il ne fleurisse pas, le figuier... moi, je veux me réjouir en l'Éternel, je veux tressaillir de joie dans le Dieu de mon salut.", reference: "Habacuc 3:17-18", theme: "Joie" },
  { text: "La lumière est semée pour le juste, et la joie pour ceux dont le cœur est droit.", reference: "Psaumes 97:11", theme: "Joie" },
  { text: "Que les justes se réjouissent, qu'ils triomphent devant Dieu, qu'ils aient des transports de joie !", reference: "Psaumes 68:4", theme: "Joie" },
  { text: "Fais de l'Éternel tes délices, et il te donnera ce que ton cœur désire.", reference: "Psaumes 37:4", theme: "Joie" },
  { text: "Je tressaille de joie en l'Éternel, mon âme est ravie d'allégresse en mon Dieu.", reference: "Ésaïe 61:10", theme: "Joie" },
  { text: "Un cœur joyeux est un bon remède, mais un esprit abattu dessèche les os.", reference: "Proverbes 17:22", theme: "Joie" },
  { text: "Vous l'aimez sans l'avoir vu, vous croyez en lui sans le voir encore, vous réjouissant d'une joie ineffable et glorieuse.", reference: "1 Pierre 1:8", theme: "Joie" },
  { text: "Le royaume de Dieu, ce n'est pas le manger et le boire, mais la justice, la paix et la joie par le Saint-Esprit.", reference: "Romains 14:17", theme: "Joie" },
  { text: "Je vous ai dit ces choses, afin que ma joie soit en vous, et que votre joie soit parfaite.", reference: "Jean 15:11", theme: "Joie" },
  { text: "Les rachetés de l'Éternel retourneront, ils iront à Sion avec des chants de triomphe, et une joie éternelle couronnera leur tête.", reference: "Ésaïe 35:10", theme: "Joie" },
  { text: "Poussez vers l'Éternel des cris de joie, vous tous, habitants de la terre !", reference: "Psaumes 100:1", theme: "Joie" },
  { text: "Béni soit le Seigneur chaque jour ! Quand nous portons un fardeau, Dieu nous sauve.", reference: "Psaumes 68:20", theme: "Joie" },
  { text: "Rendez grâces au Père, qui vous a rendus capables d'avoir part à l'héritage des saints dans la lumière.", reference: "Colossiens 1:12", theme: "Joie" },
  { text: "Puisse-t-il te donner ce que ton cœur désire, et accomplir tous tes desseins !", reference: "Psaumes 20:5", theme: "Joie" },
  { text: "À cause de cela mon cœur est dans la joie, mon esprit dans l'allégresse, et mon corps repose en sécurité.", reference: "Psaumes 16:9", theme: "Joie" },
  { text: "Le juste se réjouit en l'Éternel et cherche en lui son refuge.", reference: "Psaumes 64:11", theme: "Joie" },
  { text: "Tu mets dans mon cœur plus de joie qu'ils n'en ont quand abondent leur froment et leur moût.", reference: "Psaumes 4:8", theme: "Joie" },
  { text: "Chantez à l'Éternel, vous ses fidèles, célébrez par vos louanges sa sainteté !", reference: "Psaumes 30:5", theme: "Joie" },
  { text: "Car sa colère dure un instant, mais sa grâce toute la vie ; le soir arrivent les pleurs, et le matin l'allégresse.", reference: "Psaumes 30:6", theme: "Joie" },
  { text: "Je te loue de ce que je suis une créature si merveilleuse. Tes œuvres sont admirables.", reference: "Psaumes 139:14", theme: "Joie" },
  { text: "Que tous ceux qui cherchent l'Éternel soient dans l'allégresse et se réjouissent en lui !", reference: "Psaumes 70:5", theme: "Joie" },
  { text: "Je me réjouis de ta parole, comme celui qui trouve un grand butin.", reference: "Psaumes 119:162", theme: "Joie" },
  { text: "Que ma bouche soit remplie de tes louanges, que chaque jour elle te glorifie !", reference: "Psaumes 71:8", theme: "Joie" },
  { text: "Je chanterai l'Éternel tant que je vivrai, je célébrerai mon Dieu tant que j'existerai.", reference: "Psaumes 104:33", theme: "Joie" },
  { text: "Que mes paroles lui soient agréables ! Je veux me réjouir en l'Éternel.", reference: "Psaumes 104:34", theme: "Joie" },
  { text: "Le juste triomphe et se réjouit en Dieu.", reference: "Psaumes 68:4", theme: "Joie" },
  { text: "Servez l'Éternel avec joie.", reference: "Psaumes 100:2", theme: "Joie" },
  { text: "Éternel, tu es mon Dieu ; je t'exalterai, je célébrerai ton nom, car tu as fait des choses merveilleuses.", reference: "Ésaïe 25:1", theme: "Joie" },
  { text: "Nous nous réjouirons de ton salut, nous lèverons l'étendard au nom de notre Dieu.", reference: "Psaumes 20:6", theme: "Joie" },
  { text: "Que ton cœur me garde tes commandements, car ils prolongeront tes jours et les années de ta vie.", reference: "Proverbes 3:1-2", theme: "Joie" },
  { text: "Tu as mis de la joie dans mon cœur.", reference: "Psaumes 4:8", theme: "Joie" },
  { text: "Allégresse et joie s'approcheront, la douleur et les gémissements s'enfuiront.", reference: "Ésaïe 51:11", theme: "Joie" },
  { text: "Je chanterai ta force ; au matin je célébrerai ta bonté.", reference: "Psaumes 59:17", theme: "Joie" },
  { text: "Mon âme sera rassasiée comme de mets gras et succulents, et, avec des cris de joie sur les lèvres, ma bouche te célébrera.", reference: "Psaumes 63:6", theme: "Joie" },
  { text: "Car tu es mon secours, et je suis dans l'allégresse à l'ombre de tes ailes.", reference: "Psaumes 63:8", theme: "Joie" },
  { text: "Mon âme est attachée à toi ; ta droite me soutient.", reference: "Psaumes 63:9", theme: "Joie" },
  { text: "Les cieux se réjouissent, et la terre est dans l'allégresse.", reference: "Psaumes 96:11", theme: "Joie" },

  // 151-200 : Amour et Communion
  { text: "Car Dieu a tant aimé le monde qu'il a donné son Fils unique, afin que quiconque croit en lui ne périsse point, mais qu'il ait la vie éternelle.", reference: "Jean 3:16", theme: "Amour" },
  { text: "Un commandement nouveau que je vous donne : Aimez-vous les uns les autres ; comme je vous ai aimés, aimez-vous les uns les autres.", reference: "Jean 13:34", theme: "Amour" },
  { text: "Mais Dieu prouve son amour envers nous, en ce que, lorsque nous étions encore des pécheurs, Christ est mort pour nous.", reference: "Romains 5:8", theme: "Amour" },
  { text: "L'amour est patient, il est plein de bonté ; l'amour n'est point envieux ; l'amour ne se vante point, il ne s'enfle point d'orgueil.", reference: "1 Corinthiens 13:4", theme: "Amour" },
  { text: "Il ne fait rien d'inconvenant, il ne cherche point son intérêt, il ne s'irrite point, il ne soupçonne point le mal.", reference: "1 Corinthiens 13:5", theme: "Amour" },
  { text: "Il ne se réjouit point de l'injustice, mais il se réjouit de la vérité.", reference: "1 Corinthiens 13:6", theme: "Amour" },
  { text: "Il excuse tout, il croit tout, il espère tout, il supporte tout.", reference: "1 Corinthiens 13:7", theme: "Amour" },
  { text: "L'amour ne périt jamais.", reference: "1 Corinthiens 13:8", theme: "Amour" },
  { text: "Maintenant donc ces trois choses demeurent : la foi, l'espérance, l'amour ; mais la plus grande de ces choses, c'est l'amour.", reference: "1 Corinthiens 13:13", theme: "Amour" },
  { text: "Bien-aimés, aimons-nous les uns les autres ; car l'amour est de Dieu, et quiconque aime est né de Dieu et connaît Dieu.", reference: "1 Jean 4:7", theme: "Amour" },
  { text: "Celui qui n'aime pas n'a pas connu Dieu, car Dieu est amour.", reference: "1 Jean 4:8", theme: "Amour" },
  { text: "Et cet amour consiste, non point en ce que nous avons aimé Dieu, mais en ce qu'il nous a aimés et a envoyé son Fils comme victime expiatoire pour nos péchés.", reference: "1 Jean 4:10", theme: "Amour" },
  { text: "Nous l'aimons, parce qu'il nous a aimés le premier.", reference: "1 Jean 4:19", theme: "Amour" },
  { text: "Celui qui a mes commandements et qui les garde, c'est celui qui m'aime ; et celui qui m'aime sera aimé de my Père, je l'aimerai, et je me ferai connaître à lui.", reference: "Jean 14:21", theme: "Amour" },
  { text: "Comme le Père m'a aimé, je vous ai aussi aimés. Demeurez dans mon amour.", reference: "Jean 15:9", theme: "Amour" },
  { text: "Il n'y a pas de plus grand amour que de donner sa vie pour ses amis.", reference: "Jean 15:13", theme: "Amour" },
  { text: "L'amour ne fait point de mal au prochain : l'amour est donc l'accomplissement de la loi.", reference: "Romains 13:10", theme: "Amour" },
  { text: "Que l'amour soit sans hypocrisie. Ayez le mal en horreur ; attachez-vous fortement au bien.", reference: "Romains 12:9", theme: "Amour" },
  { text: "Par amour fraternel, soyez pleins d'affection les uns pour les autres ; par honneur, usez de prévenances réciproques.", reference: "Romains 12:10", theme: "Amour" },
  { text: "Mais au-dessus de toutes ces choses revêtez-vous de l'amour, qui est le lien de la perfection.", reference: "Colossiens 3:14", theme: "Amour" },
  { text: "Car l'amour de Christ nous presse, parce que nous estimons que, si un seul est mort pour tous, tous donc sont morts.", reference: "2 Corinthiens 5:14", theme: "Amour" },
  { text: "La grâce du Seigneur Jésus-Christ, l'amour de Dieu, et la communion du Saint-Esprit, soient avec vous tous !", reference: "2 Corinthiens 13:13", theme: "Amour" },
  { text: "Car le Père lui-même vous aime, parce que vous m'avez aimé, et que vous avez cru que je suis sorti de Dieu.", reference: "Jean 16:27", theme: "Amour" },
  { text: "La haine excite des querelles, mais l'amour couvre toutes les fautes.", reference: "Proverbes 10:12", theme: "Amour" },
  { text: "Mieux vaut un plat de légumes, là où il y a de l'amour, qu'un bœuf gras, si la haine est là.", reference: "Proverbes 15:17", theme: "Amour" },
  { text: "L'ami aime en tout temps, et dans le malheur il se montre un frère.", reference: "Proverbes 17:17", theme: "Amour" },
  { text: "Met-moi comme un sceau sur ton cœur, comme un sceau sur ton bras ; car l'amour est fort comme la mort.", reference: "Song of Solomon 8:6", theme: "Amour" },
  { text: "Les grandes eaux ne peuvent éteindre l'amour, et les fleuves ne le submergeraient pas.", reference: "Song of Solomon 8:7", theme: "Amour" },
  { text: "N'aimons pas en paroles et avec la langue, mais en actions et avec vérité.", reference: "1 Jean 3:18", theme: "Amour" },
  { text: "La crainte n'est pas dans l'amour, mais l'amour parfait bannit la crainte.", reference: "1 Jean 4:18", theme: "Amour" },
  { text: "Quiconque confesse que Jésus est le Fils de Dieu, Dieu demeure en lui, et lui en Dieu.", reference: "1 Jean 4:15", theme: "Amour" },
  { text: "Dieu demeure en nous, et son amour est parfait en nous.", reference: "1 Jean 4:12", theme: "Amour" },
  { text: "Que la grâce, la miséricorde et la paix soient avec vous de la part de Dieu le Père.", reference: "2 Jean 1:3", theme: "Amour" },
  { text: "Marchez dans l'amour, à l'exemple de Christ, qui nous a aimés, et s'est livré lui-même à Dieu pour nous.", reference: "Éphésiens 5:2", theme: "Amour" },
  { text: "Que le Seigneur fasse abonder et déborder votre amour les uns pour les autres et pour tous.", reference: "1 Thessaloniciens 3:12", theme: "Amour" },
  { text: "Ayez les uns pour les autres un ardent amour, car l'amour couvre une multitude de péchés.", reference: "1 Pierre 4:8", theme: "Amour" },
  { text: "L'amour de Dieu a été répandu dans nos cœurs par le Saint-Esprit qui nous a été donné.", reference: "Romains 5:5", theme: "Amour" },
  { text: "Tu aimeras le Seigneur, ton Dieu, de tout ton cœur, de toute ton âme, de toute ta force, et de toute ta pensée ; et ton prochain comme toi-même.", reference: "Luc 10:27", theme: "Amour" },
  { text: "Si je parle les langues des hommes et des anges, mais que je n'ai pas l'amour, je suis un bronze qui résonne.", reference: "1 Corinthiens 13:1", theme: "Amour" },
  { text: "Dieu est fidèle, lui qui vous a appelés à la communion de son Fils, Jésus-Christ notre Seigneur.", reference: "1 Corinthiens 1:9", theme: "Amour" },
  { text: "Voici, qu'il est agréable, qu'il est doux pour des frères de demeurer ensemble !", reference: "Psaumes 133:1", theme: "Amour" },
  { text: "Je vous appelle mes amis, parce que je vous ai fait connaître tout ce que j'ai appris de mon Père.", reference: "Jean 15:15", theme: "Amour" },
  { text: "Demeurez en moi, et je demeurerai en vous.", reference: "Jean 15:4", theme: "Amour" },
  { text: "Je suis le cep, vous êtes les sarments. Celui qui demeure en moi et en qui je demeure porte beaucoup de fruit.", reference: "Jean 15:5", theme: "Amour" },
  { text: "Si vous demeurez en moi, et que mes paroles demeurent en vous, demandez ce que vous voudrez, et cela vous sera accordé.", reference: "Jean 15:7", theme: "Amour" },
  { text: "Ce n'est pas vous qui m'avez choisi ; mais moi, je vous ai choisis, et je vous ai établis, afin que vous alliez, et que vous portiez du fruit.", reference: "Jean 15:16", theme: "Amour" },
  { text: "Mais notre communion est avec le Père et avec son Fils Jésus-Christ.", reference: "1 Jean 1:3", theme: "Amour" },
  { text: "Si nous marchons dans la lumière, comme il est lui-même dans la lumière, nous sommes en communion les uns avec les autres.", reference: "1 Jean 1:7", theme: "Amour" },
  { text: "Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner, et pour nous purifier de toute iniquité.", reference: "1 Jean 1:9", theme: "Amour" },
  { text: "Voici, je me tiens à la porte, et je frappe. Si quelqu'un entend ma voix et ouvre la porte, j'entrerai chez lui, je souperai avec lui, et lui avec moi.", reference: "Revelation 3:20", theme: "Amour" },

  // 201-250 : Sagesse et Discernement
  { text: "Le commencement de la sagesse, c'est la crainte de l'Éternel ; et la science des saints, c'est l'intelligence.", reference: "Proverbes 9:10", theme: "Sagesse" },
  { text: "Si quelqu'un d'entre vous manque de sagesse, qu'il la demande à Dieu, qui donne à tous simplement et sans reproche, et elle lui sera donnée.", reference: "Jacques 1:5", theme: "Sagesse" },
  { text: "Heureux l'homme qui a trouvé la sagesse, et l'homme qui possède l'intelligence !", reference: "Proverbes 3:13", theme: "Sagesse" },
  { text: "Car le gain qu'elle procure est préférable à celui de l'argent, et le produit qu'elle donne vaut mieux que l'or.", reference: "Proverbes 3:14", theme: "Sagesse" },
  { text: "Elle est plus précieuse que les perles, elle a plus de valeur que tous les objets de ton désir.", reference: "Proverbes 3:15", theme: "Sagesse" },
  { text: "Dans sa droite est une longue vie ; dans sa gauche sont la richesse et la gloire.", reference: "Proverbes 3:16", theme: "Sagesse" },
  { text: "Ses voies sont des voies agréables, et tous ses sentiers sont paisibles.", reference: "Proverbes 3:17", theme: "Sagesse" },
  { text: "Elle est un arbre de vie pour ceux qui la saisissent, et ceux qui la possèdent sont heureux.", reference: "Proverbes 3:18", theme: "Sagesse" },
  { text: "La sagesse d'en haut est d'abord pure, ensuite pacifique, modérée, conciliante, pleine de miséricorde et de bons fruits.", reference: "Jacques 3:17", theme: "Sagesse" },
  { text: "Car l'Éternel donne la sagesse ; de sa bouche sortent la connaissance et l'intelligence.", reference: "Proverbes 2:6", theme: "Sagesse" },
  { text: "Il tient en réserve le salut pour les hommes droits, un bouclier pour ceux qui marchent dans l'intégrité.", reference: "Proverbes 2:7", theme: "Sagesse" },
  { text: "Alors tu comprendras la justice, l'équité, la droiture, toutes les routes qui mènent au bien.", reference: "Proverbes 2:9", theme: "Sagesse" },
  { text: "Car la sagesse viendra dans ton cœur, et la connaissance fera les délices de ton âme.", reference: "Proverbes 2:10", theme: "Sagesse" },
  { text: "La réflexion veillera sur toi, l'intelligence te gardera.", reference: "Proverbes 2:11", theme: "Sagesse" },
  { text: "Acquiers la sagesse, acquiers l'intelligence ; n'oublie pas les paroles de ma bouche, et ne t'en détourne pas.", reference: "Proverbes 4:5", theme: "Sagesse" },
  { text: "Ne l'abandonne pas, et elle te gardera ; aime-la, et elle te protégera.", reference: "Proverbes 4:6", theme: "Sagesse" },
  { text: "Voici le commencement de la sagesse : Acquiers la sagesse, et avec tout ce que tu possèdes acquiers l'intelligence.", reference: "Proverbes 4:7", theme: "Sagesse" },
  { text: "Exalte-la, et elle t'élèvera ; elle fera ta gloire, si tu l'embrasses.", reference: "Proverbes 4:8", theme: "Sagesse" },
  { text: "Elle mettra sur ta tête une couronne de grâce, elle t'ornera d'un magnifique diadème.", reference: "Proverbes 4:9", theme: "Sagesse" },
  { text: "La sagesse est une source de vie pour celui qui la possède.", reference: "Proverbes 16:22", theme: "Sagesse" },
  { text: "Combien acquérir la sagesse vaut mieux que l'or ! Combien acquérir l'intelligence est préférable à l'argent !", reference: "Proverbes 16:16", theme: "Sagesse" },
  { text: "Celui qui réfléchit sur les choses trouve le bonheur, et celui qui se confie en l'Éternel est heureux.", reference: "Proverbes 16:20", theme: "Sagesse" },
  { text: "Celui qui est sage de cœur est appelé intelligent, et la douceur des lèvres augmente la science.", reference: "Proverbes 16:21", theme: "Sagesse" },
  { text: "Les paroles de la bouche d'un homme sage sont pleines de grâce.", reference: "Ecclésiaste 10:12", theme: "Sagesse" },
  { text: "La sagesse vaut mieux que les instruments de guerre.", reference: "Ecclésiaste 9:18", theme: "Sagesse" },
  { text: "La sagesse rend le sage plus fort que dix chefs qui sont dans une ville.", reference: "Ecclésiaste 7:19", theme: "Sagesse" },
  { text: "Car la sagesse est une défense, tout comme l'argent est une défense ; mais l'excellence de la connaissance, c'est que la sagesse préserve la vie de ceux qui la possèdent.", reference: "Ecclésiaste 7:12", theme: "Sagesse" },
  { text: "Qui est sage ? Qu'il prenne garde à ces choses ! Et qu'il médite sur les bontés de l'Éternel.", reference: "Psaumes 107:43", theme: "Sagesse" },
  { text: "Enseigne-nous à bien compter nos jours, afin que nous appliquions notre cœur à la sagesse.", reference: "Psaumes 90:12", theme: "Sagesse" },
  { text: "La loi de l'Éternel est parfaite, elle restaure l'âme ; le témoignage de l'Éternel est véritable, il rend sage l'ignorant.", reference: "Psaumes 19:8", theme: "Sagesse" },
  { text: "C'est en Christ que sont cachés tous les trésors de la sagesse et de la science.", reference: "Colossiens 2:3", theme: "Sagesse" },
  { text: "Que la parole de Christ habite parmi vous abondamment ; instruisez-vous et exhortez-vous les uns les autres en toute sagesse.", reference: "Colossiens 3:16", theme: "Sagesse" },
  { text: "Conduisez-vous avec sagesse envers ceux du dehors, en rachetant le temps.", reference: "Colossiens 4:5", theme: "Sagesse" },
  { text: "Que votre parole soit toujours accompagnée de grâce, assaisonnée de sel, afin que vous sachiez comment il faut répondre à chacun.", reference: "Colossiens 4:6", theme: "Sagesse" },
  { text: "L'oreille qui écoute les avertissements de la vie fait son séjour au milieu des sages.", reference: "Proverbes 15:31", theme: "Sagesse" },
  { text: "La crainte de l'Éternel enseigne la sagesse, et l'humilité précède la gloire.", reference: "Proverbes 15:33", theme: "Sagesse" },
  { text: "Les desseins échouent faute de délibération, mais ils réussissent quand il y a de nombreux conseillers.", reference: "Proverbes 15:22", theme: "Sagesse" },
  { text: "Le cœur de l'homme intelligent acquiert la connaissance, et l'oreille des sages la cherche.", reference: "Proverbes 18:15", theme: "Sagesse" },
  { text: "Celui qui fréquente les sages devient sage, mais celui qui se plaît avec les insensés s'en trouve mal.", reference: "Proverbes 13:20", theme: "Sagesse" },
  { text: "La sagesse du sage, c'est l'intelligence de sa voie ; la folie des insensés, c'est la tromperie.", reference: "Proverbes 14:8", theme: "Sagesse" },
  { text: "Le sage craint et se détourne du mal, mais l'insensé est arrogant et plein de sécurité.", reference: "Proverbes 14:16", theme: "Sagesse" },
  { text: "Le cœur intelligent cherche la science, mais la bouche des insensés se nourrit de folie.", reference: "Proverbes 15:14", theme: "Sagesse" },
  { text: "Ne parle pas aux oreilles de l'insensé, car il méprise le bon sens de tes discours.", reference: "Proverbes 23:9", theme: "Sagesse" },
  { text: "Par la sagesse une maison s'élève, et par l'intelligence elle s'affermit.", reference: "Proverbes 24:3", theme: "Sagesse" },
  { text: "Par la science les chambres se remplissent de tous les biens précieux et agréables.", reference: "Proverbes 24:4", theme: "Sagesse" },
  { text: "Un homme sage est plein de force, et celui qui a de la science affermit sa vigueur.", reference: "Proverbes 24:5", theme: "Sagesse" },
  { text: "Car tu fais la guerre avec prudence, et le salut est dans le grand nombre des conseillers.", reference: "Proverbes 24:6", theme: "Sagesse" },
  { text: "La sagesse est trop haute pour l'insensé ; il n'ouvrira pas la bouche à la porte.", reference: "Proverbes 24:7", theme: "Sagesse" },
  { text: "Mon fils, mange du miel, car il est bon ; un rayon de miel sera doux à ton palais. De même, connais la sagesse pour ton âme.", reference: "Proverbes 24:13-14", theme: "Sagesse" },
  { text: "Si tu la trouves, il y a un avenir, et ton espérance ne sera pas anéantie.", reference: "Proverbes 24:14", theme: "Sagesse" },

  // 251-500 : Extension automatique pour atteindre exactement 500 versets variés.
  // Pour garder de la variété théologique et thématique réelle, nous déclinons les thèmes restants :
  // Espérance, Force & Courage, Grâce & Rédemption, Prière & Exaucement, Guidance & Protection.
  // 251-300 : Espérance et Avenir
  { text: "Car je connais les projets que j'ai formés sur vous, dit l'Éternel, projets de paix et non de malheur, afin de vous donner un avenir et de l'espérance.", reference: "Jérémie 29:11", theme: "Espérance" },
  { text: "Mais ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles ; ils courent, et ne se lassent point.", reference: "Ésaïe 40:31", theme: "Espérance" },
  { text: "L'espérance ne trompe point, parce que l'amour de Dieu est répandu dans nos cœurs par le Saint-Esprit qui nous a été donné.", reference: "Romains 5:5", theme: "Espérance" },
  { text: "Le Dieu d'espérance vous remplisse de toute joie et de toute paix dans la foi, pour que vous abondiez en espérance, par la puissance du Saint-Esprit.", reference: "Romains 15:13", theme: "Espérance" },
  { text: "Car nous sommes sauvés en espérance. Or, l'espérance qu'on voit n'est plus espérance : ce qu'on voit, peut-on l'espérer encore ?", reference: "Romains 8:24", theme: "Espérance" },
  { text: "Et si nous espérons ce que nous ne voyons pas, nous l'attendons avec persévérance.", reference: "Romains 8:25", theme: "Espérance" },
  { text: "Soyez joyeux en espérance. Soyez patients dans la affliction. Persévérez dans la prière.", reference: "Romains 12:12", theme: "Espérance" },
  { text: "Il y a de l'espérance pour ton avenir, dit l'Éternel ; tes enfants reviendront dans leur pays.", reference: "Jérémie 31:17", theme: "Espérance" },
  { text: "Le juste trouve un refuge même en sa mort.", reference: "Proverbes 14:32", theme: "Espérance" },
  { text: "Attends-toi à l'Éternel ! Fortifie-toi et que ton cœur s'affermisse ! Attends-toi à l'Éternel !", reference: "Psaumes 27:14", theme: "Espérance" },
  { text: "Oui, mon âme, confie-toi en Dieu, car de lui vient mon espérance.", reference: "Psaumes 62:6", theme: "Espérance" },
  { text: "Éternel, tu es mon refuge, ma part sur la terre des vivants.", reference: "Psaumes 142:6", theme: "Espérance" },
  { text: "Christ en vous, l'espérance de la gloire.", reference: "Colossiens 1:27", theme: "Espérance" },
  { text: "Cette espérance, nous la possédons comme une ancre de l'âme, sûre et solide.", reference: "Hébreux 6:19", theme: "Espérance" },
  { text: "Béni soit le Dieu et Père de notre Seigneur Jésus-Christ, qui nous a régénérés pour une espérance vivante.", reference: "1 Pierre 1:3", theme: "Espérance" },
  { text: "Espérez constamment dans la grâce qui vous sera apportée, à la révélation de Jésus-Christ.", reference: "1 Pierre 1:13", theme: "Espérance" },
  { text: "Étant toujours prêts à vous défendre, avec douceur et respect, devant quiconque vous demande raison de l'espérance qui est en vous.", reference: "1 Pierre 3:15", theme: "Espérance" },
  { text: "L'Éternel a des regards de bienveillance sur ceux qui espèrent en sa bonté.", reference: "Psaumes 33:18", theme: "Espérance" },
  { text: "Que ta bonté, ô Éternel ! soit sur nous, comme nous espérons en toi !", reference: "Psaumes 33:22", theme: "Espérance" },
  { text: "Pourquoi t'abats-tu, mon âme, et gémis-tu au-dedans de moi ? Espère en Dieu, car je le louerai encore.", reference: "Psaumes 42:6", theme: "Espérance" },
  { text: "Il est mon salut et ma gloire ; le rocher de ma force, mon refuge est en Dieu.", reference: "Psaumes 62:8", theme: "Espérance" },
  { text: "Tu es mon refuge et mon bouclier ; j'espère en ta promesse.", reference: "Psaumes 119:114", theme: "Espérance" },
  { text: "Soutiens-moi selon ta promesse, afin que je vive, et ne me rends pas confus dans mon espérance !", reference: "Psaumes 119:116", theme: "Espérance" },
  { text: "Mon âme soupire après ton salut ; j'espère en ta promesse.", reference: "Psaumes 119:81", theme: "Espérance" },
  { text: "J'espère en l'Éternel, mon âme espère, et j'attends sa promesse.", reference: "Psaumes 130:5", theme: "Espérance" },
  { text: "Mon âme compte sur le Seigneur, plus que les gardes ne comptent sur le matin.", reference: "Psaumes 130:6", theme: "Espérance" },
  { text: "Israël, mets ton espérance en l'Éternel, car la miséricorde est auprès de l'Éternel.", reference: "Psaumes 130:7", theme: "Espérance" },
  { text: "Heureux celui qui a pour secours le Dieu de Jacob, qui met son espérance en l'Éternel, son Dieu !", reference: "Psaumes 146:5", theme: "Espérance" },
  { text: "L'Éternel aime ceux qui le craignent, ceux qui espèrent en sa bonté.", reference: "Psaumes 147:11", theme: "Espérance" },
  { text: "L'espérance des justes n'est que joie, mais l'attente des méchants périra.", reference: "Proverbes 10:28", theme: "Espérance" },
  { text: "Il y a pour l'arbre de l'espérance : quand on le coupe, il repousse encore.", reference: "Job 14:7", theme: "Espérance" },
  { text: "Tu seras plein de confiance, et ton attente ne sera pas vaine ; tu regarderas autour de toi, et tu te coucheras en sûreté.", reference: "Job 11:18", theme: "Espérance" },
  { text: "Car Dieu n'est pas injuste, pour oublier votre travail et l'amour que vous avez montré pour son nom.", reference: "Hébreux 6:10", theme: "Espérance" },
  { text: "Retenons fermement la profession de notre espérance, car celui qui a fait la promesse est fidèle.", reference: "Hébreux 10:23", theme: "Espérance" },
  { text: "Ne rejetez donc pas votre assurance, à laquelle est attachée une grande rémunération.", reference: "Hébreux 10:35", theme: "Espérance" },
  { text: "Car vous avez besoin de persévérance, afin qu'après avoir accompli la volonté de Dieu, vous obteniez ce qui vous est promis.", reference: "Hébreux 10:36", theme: "Espérance" },
  { text: "Encore un peu, un peu de temps : celui qui doit venir viendra, et il ne tardera pas.", reference: "Hébreux 10:37", theme: "Espérance" },
  { text: "Nous attendons, selon sa promesse, de nouveaux cieux et une nouvelle terre, où la justice habitera.", reference: "2 Pierre 3:13", theme: "Espérance" },
  { text: "Bien-aimés, nous sommes maintenant enfants de Dieu, et ce que nous serons n'a pas encore été manifesté.", reference: "1 Jean 3:2", theme: "Espérance" },
  { text: "Quiconque a cette espérance en lui se purifie, comme lui-même est pur.", reference: "1 Jean 3:3", theme: "Espérance" },
  { text: "Celui qui vaincra héritera ces choses ; je serai son Dieu, et il sera mon fils.", reference: "Revelation 21:7", theme: "Espérance" },
  { text: "Il n'y aura plus de nuit ; et ils n'auront besoin ni de la lumière du flambeau, ni de la lumière du soleil, parce que le Seigneur Dieu les éclairera.", reference: "Revelation 22:5", theme: "Espérance" },
  { text: "Voici, je viens bientôt, et ma rétribution est avec moi, pour rendre à chacun selon son œuvre.", reference: "Revelation 22:12", theme: "Espérance" },
  { text: "Celui qui atteste ces choses dit : Oui, je viens bientôt. Amen ! Viens, Seigneur Jésus !", reference: "Revelation 22:20", theme: "Espérance" },
  { text: "Que la grâce du Seigneur Jésus soit avec tous !", reference: "Revelation 22:21", theme: "Espérance" },
  { text: "L'Éternel est bon pour ceux qui espèrent en lui, pour l'âme qui le cherche.", reference: "Lamentations 3:25", theme: "Espérance" },
  { text: "Il est bon d'attendre en silence le secours de l'Éternel.", reference: "Lamentations 3:26", theme: "Espérance" },
  { text: "Car le Seigneur ne rejette pas à toujours.", reference: "Lamentations 3:31", theme: "Espérance" },
  { text: "Mais, quand il afflige, il a compassion selon sa grande bonté.", reference: "Lamentations 3:32", theme: "Espérance" },
  { text: "Car ce n'est pas volontiers qu'il humilie et qu'il afflige les enfants des hommes.", reference: "Lamentations 3:33", theme: "Espérance" },

  // 301-350 : Force et Courage
  { text: "Fortifiez-vous et prenez courage, vous tous qui espérez en l'Éternel !", reference: "Psaumes 31:25", theme: "Force" },
  { text: "Ne crains rien, car je suis avec toi ; ne promène pas des regards inquiets, car je suis ton Dieu ; je te fortifie, je viens à ton secours.", reference: "Ésaïe 41:10", theme: "Force" },
  { text: "Il donne de la force à celui qui est fatigué, et il augmente la vigueur de celui qui tombe en défaillance.", reference: "Ésaïe 40:29", theme: "Force" },
  { text: "Les adolescents se fatiguent et se lassent, et les jeunes hommes chancellent.", reference: "Ésaïe 40:30", theme: "Force" },
  { text: "L'Éternel est ma force et le sujet de mes louanges ; c'est lui qui m'a sauvé.", reference: "Exode 15:2", theme: "Force" },
  { text: "Ma chair et mon cœur peuvent se consumer : Dieu est le rocher de mon cœur et ma part pour toujours.", reference: "Psaumes 73:26", theme: "Force" },
  { text: "Dieu est notre refuge et notre force, un secours toujours présent dans la détresse.", reference: "Psaumes 46:2", theme: "Force" },
  { text: "C'est pourquoi nous sommes sans crainte quand la terre est bouleversée, et que les montagnes chancellent au cœur des mers.", reference: "Psaumes 46:3", theme: "Force" },
  { text: "L'Éternel des armées est avec nous, le Dieu de Jacob est pour nous une haute retraite.", reference: "Psaumes 46:8", theme: "Force" },
  { text: "Arrêtez, et sachez que je suis Dieu : je domine sur les nations, je domine sur la terre.", reference: "Psaumes 46:11", theme: "Force" },
  { text: "Le nom de l'Éternel est une tour forte ; le juste s'y réfugie, et s'y trouve en sécurité.", reference: "Proverbes 18:10", theme: "Force" },
  { text: "Si tu faiblis au jour de la détresse, ta force est bien peu de chose.", reference: "Proverbes 24:10", theme: "Force" },
  { text: "Ne vous affligez pas, car la joie de l'Éternel sera votre force.", reference: "Néhémie 8:10", theme: "Force" },
  { text: "L'Éternel est ma lumière et mon salut : De qui aurais-je crainte ? L'Éternel est le soutien de ma vie : De qui aurais-je peur ?", reference: "Psaumes 27:1", theme: "Force" },
  { text: "Une chose que j'ai demandée à l'Éternel, et que je désire ardemment : habiter toute ma vie dans la maison de l'Éternel.", reference: "Psaumes 27:4", theme: "Force" },
  { text: "Car il me protégera dans son tabernacle au jour du malheur, il me cachera sous l'abri de sa tente.", reference: "Psaumes 27:5", theme: "Force" },
  { text: "Écoute, Éternel ! ma voix que j'élève ; aie pitié de moi et exauce-moi !", reference: "Psaumes 27:7", theme: "Force" },
  { text: "Mon cœur dit de ta part : Cherchez ma face ! Je cherche ta face, ô Éternel !", reference: "Psaumes 27:8", theme: "Force" },
  { text: "Ne me cache pas ta face, ne repousse pas avec colère ton serviteur ! Tu es mon secours.", reference: "Psaumes 27:9", theme: "Force" },
  { text: "Car mon père et ma mère m'abandonnent, mais l'Éternel me recueillera.", reference: "Psaumes 27:10", theme: "Force" },
  { text: "Je suis sûr de voir la bonté de l'Éternel sur la terre des vivants.", reference: "Psaumes 27:13", theme: "Force" },
  { text: "Fortifie-toi et que ton cœur s'affermisse ; attends-toi à l'Éternel !", reference: "Psaumes 27:14", theme: "Force" },
  { text: "Le Seigneur est ma force et mon bouclier.", reference: "Psaumes 28:7", theme: "Force" },
  { text: "L'Éternel est la force de son peuple, il est le rempart des délivrances de son oint.", reference: "Psaumes 28:8", theme: "Force" },
  { text: "Sauve ton peuple et bénis ton héritage ! Sois leur berger et leur soutien pour toujours !", reference: "Psaumes 28:9", theme: "Force" },
  { text: "Je t'aime, ô Éternel, ma force !", reference: "Psaumes 18:2", theme: "Force" },
  { text: "Éternel, mon rocher, ma forteresse, mon libérateur ! Mon Dieu, mon rocher, où je trouve un abri !", reference: "Psaumes 18:3", theme: "Force" },
  { text: "Mon bouclier, la force qui me sauve, ma haute retraite !", reference: "Psaumes 18:3", theme: "Force" },
  { text: "Je m'écrie : Loué soit l'Éternel ! Et je suis délivré de mes ennemis.", reference: "Psaumes 18:4", theme: "Force" },
  { text: "C'est Dieu qui me ceint de force, et qui me trace une voie droite.", reference: "Psaumes 18:33", theme: "Force" },
  { text: "Il rend mes pieds semblables à ceux des biches, et il me place sur mes hauteurs.", reference: "Psaumes 18:34", theme: "Force" },
  { text: "Tu me donnes le bouclier de ton salut, ta droite me soutient, et je deviens grand par ta bonté.", reference: "Psaumes 18:36", theme: "Force" },
  { text: "Tu élargis le chemin sous mes pas, et mes pieds ne chancellent point.", reference: "Psaumes 18:37", theme: "Force" },
  { text: "Je poursuis mes ennemis, je les atteins, et je ne reviens pas avant de les avoir anéantis.", reference: "Psaumes 18:38", theme: "Force" },
  { text: "Tu me ceins de force pour le combat, tu plies sous moi mes adversaires.", reference: "Psaumes 18:40", theme: "Force" },
  { text: "Vive l'Éternel, et béni soit mon rocher ! Que le Dieu de mon salut soit exalté !", reference: "Psaumes 18:47", theme: "Force" },
  { text: "Au reste, fortifiez-vous dans le Seigneur, et par sa force toute-puissante.", reference: "Éphésiens 6:10", theme: "Force" },
  { text: "Revêtez-vous de toutes les armes de Dieu, afin de pouvoir tenir ferme contre les ruses du diable.", reference: "Éphésiens 6:11", theme: "Force" },
  { text: "C'est pourquoi, prenez toutes les armes de Dieu, afin de pouvoir résister dans le mauvais jour, et tenir ferme après avoir tout surmonté.", reference: "Éphésiens 6:13", theme: "Force" },
  { text: "Tenez ferme donc : ayez à vos reins la vérité pour ceinture ; revêtez la cuirasse de la justice.", reference: "Éphésiens 6:14", theme: "Force" },
  { text: "Mettez pour chaussures à vos pieds le zèle que donne l'Évangile de paix.", reference: "Éphésiens 6:15", theme: "Force" },
  { text: "Prenez par-dessus tout cela le bouclier de la foi, avec lequel vous pourrez éteindre tous les traits enflammés du malin.", reference: "Éphésiens 6:16", theme: "Force" },
  { text: "Prenez aussi le casque du salut, et l'épée de l'Esprit, qui est la parole de Dieu.", reference: "Éphésiens 6:17", theme: "Force" },
  { text: "Faites en tout temps par l'Esprit toutes sortes de prières et de supplications.", reference: "Éphésiens 6:18", theme: "Force" },
  { text: "Veillez à cela avec une entière persévérance, et priez pour tous les saints.", reference: "Éphésiens 6:18", theme: "Force" },
  { text: "Veillez, demeurez fermes dans la foi, soyez des hommes, fortifiez-vous.", reference: "1 Corinthiens 16:13", theme: "Force" },
  { text: "Que tout ce que vous faites se fasse avec amour.", reference: "1 Corinthiens 16:14", theme: "Force" },
  { text: "Car ce n'est pas un esprit de timidité que Dieu nous a donné, mais un esprit de force, d'amour et de sagesse.", reference: "2 Timothée 1:7", theme: "Force" },
  { text: "Ne rougis donc point du témoignage à rendre à notre Seigneur.", reference: "2 Timothée 1:8", theme: "Force" },
  { text: "Toi donc, mon enfant, fortifie-toi dans la grâce qui est en Jésus-Christ.", reference: "2 Timothée 2:1", theme: "Force" },

  // 351-400 : Grâce et Rédemption
  { text: "Car le salaire du péché, c'est la mort ; mais le don gratuit de Dieu, c'est la vie éternelle en Jésus-Christ notre Seigneur.", reference: "Romains 6:23", theme: "Grâce" },
  { text: "Car la grâce de Dieu, source de salut pour tous les hommes, a été manifestée.", reference: "Tite 2:11", theme: "Grâce" },
  { text: "Mais la loi est intervenue pour que l'offense abondât ; mais là où le péché a abondé, la grâce a surabondé.", reference: "Romains 5:20", theme: "Grâce" },
  { text: "C'est par la grâce que vous êtes sauvés.", reference: "Éphésiens 2:5", theme: "Grâce" },
  { text: "Et il m'a dit : Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse.", reference: "2 Corinthiens 12:9", theme: "Grâce" },
  { text: "Je me glorifierai donc bien plus volontiers de mes faiblesses, afin que la puissance de Christ repose sur moi.", reference: "2 Corinthiens 12:9", theme: "Grâce" },
  { text: "C'est pourquoi je me plais dans les faiblesses, dans les outrages, dans les calamités, dans les persécutions, dans les détresses, pour Christ ; car, quand je suis faible, c'est alors que je suis fort.", reference: "2 Corinthiens 12:10", theme: "Grâce" },
  { text: "Approchons-nous donc avec assurance du trône de la grâce, afin d'obtenir miséricorde et de trouver grâce, pour être secourus dans nos besoins.", reference: "Hébreux 4:16", theme: "Grâce" },
  { text: "Car vous connaissez la grâce de notre Seigneur Jésus-Christ, qui pour vous s'est fait pauvre, de riche qu'il était, afin que par sa pauvreté vous fussiez enrichis.", reference: "2 Corinthiens 8:9", theme: "Grâce" },
  { text: "Et Dieu peut vous combler de toutes sortes de grâces, afin que, possédant toujours en toutes choses de quoi satisfaire à vos besoins, vous ayez encore en abondance pour toute bonne œuvre.", reference: "2 Corinthiens 9:8", theme: "Grâce" },
  { text: "Car tous ont péché et sont privés de la gloire de Dieu ; et ils sont gratuitement justifiés par sa grâce, par le moyen de la rédemption qui est en Jésus-Christ.", reference: "Romains 3:23-24", theme: "Grâce" },
  { text: "En lui nous avons la rédemption par son sang, le pardon des péchés, selon la richesse de sa grâce.", reference: "Éphésiens 1:7", theme: "Grâce" },
  { text: "Dieu nous a sauvés, et nous a adressé un saint appel, non à cause de nos œuvres, mais selon son propre dessein, et selon la grâce qui nous a été donnée en Jésus-Christ avant les temps éternels.", reference: "2 Timothée 1:9", theme: "Grâce" },
  { text: "Rendons grâces au Seigneur, car il est bon, car sa miséricorde dure à toujours.", reference: "Psaumes 106:1", theme: "Grâce" },
  { text: "Éternel, que ta grâce soit sur nous, comme nous espérons en toi !", reference: "Psaumes 33:22", theme: "Grâce" },
  { text: "Mais Dieu, qui est riche en miséricorde, à cause du grand amour dont il nous a aimés, nous a rendus à la vie avec Christ.", reference: "Éphésiens 2:4-5", theme: "Grâce" },
  { text: "Et il nous a ressuscités ensemble, et nous a fait asseoir ensemble dans les lieux célestes, en Jésus-Christ.", reference: "Éphésiens 2:6", theme: "Grâce" },
  { text: "Afin de montrer dans les âges à venir la richesse infinie de sa grâce par sa bonté envers nous en Jésus-Christ.", reference: "Éphésiens 2:7", theme: "Grâce" },
  { text: "Car c'est par la grâce que vous êtes sauvés, par le moyen de la foi. Et cela ne vient pas de vous, c'est le don de Dieu. Ce n'est point par les œuvres, afin que personne ne se glorifie.", reference: "Éphésiens 2:8-9", theme: "Grâce" },
  { text: "Car nous sommes son ouvrage, ayant été créés en Jésus-Christ pour de bonnes œuvres.", reference: "Éphésiens 2:10", theme: "Grâce" },
  { text: "La grâce et la vérité sont venues par Jésus-Christ.", reference: "Jean 1:17", theme: "Grâce" },
  { text: "Et de sa plénitude nous avons tous reçu, et grâce pour grâce.", reference: "Jean 1:16", theme: "Grâce" },
  { text: "Que la grâce du Seigneur Jésus-Christ soit avec votre esprit !", reference: "Philémon 1:25", theme: "Grâce" },
  { text: "Il donne, au contraire, une grâce plus excellente ; c'est pourquoi l'Écriture dit : Dieu résiste aux orgueilleux, mais il fait grâce aux humbles.", reference: "Jacques 4:6", theme: "Grâce" },
  { text: "Soumettez-vous donc à Dieu ; résistez au diable, et il fuira loin de vous.", reference: "Jacques 4:7", theme: "Grâce" },
  { text: "Approchez-vous de Dieu, et il s'approchera de vous.", reference: "Jacques 4:8", theme: "Grâce" },
  { text: "Humiliez-vous devant le Seigneur, et il vous élèvera.", reference: "Jacques 4:10", theme: "Grâce" },
  { text: "Croissez dans la grâce et dans la connaissance de notre Seigneur et Sauveur Jésus-Christ. À lui soit la gloire, maintenant et pour l'éternité ! Amen !", reference: "2 Pierre 3:18", theme: "Grâce" },
  { text: "Que la grâce et la paix vous soient multipliées par la connaissance de Dieu et de Jésus notre Seigneur !", reference: "2 Pierre 1:2", theme: "Grâce" },
  { text: "Sa divine puissance nous a donné tout ce qui contribue à la vie et à la piété.", reference: "2 Pierre 1:3", theme: "Grâce" },
  { text: "Par lesquelles nous ont été données les plus grandes et les plus précieuses promesses, afin que par elles vous deveniez participants de la nature divine.", reference: "2 Pierre 1:4", theme: "Grâce" },
  { text: "Faites tous vos efforts pour joindre à votre foi la vertu, à la vertu la science.", reference: "2 Pierre 1:5", theme: "Grâce" },
  { text: "À la science la tempérance, à la tempérance la patience, à la patience la piété.", reference: "2 Pierre 1:6", theme: "Grâce" },
  { text: "À la piété l'amour fraternel, à l'amour fraternel la charité.", reference: "2 Pierre 1:7", theme: "Grâce" },
  { text: "Car si ces choses sont en vous, et y abondent, elles ne vous laisseront point oisifs ni stériles pour la connaissance de notre Seigneur Jésus-Christ.", reference: "2 Pierre 1:8", theme: "Grâce" },
  { text: "C'est pourquoi, frères, appliquez-vous d'autant plus à affermir votre vocation et votre élection ; car, en faisant cela, vous ne broncherez jamais.", reference: "2 Pierre 1:10", theme: "Grâce" },
  { text: "C'est ainsi que l'entrée dans le royaume éternel de notre Seigneur et Sauveur Jésus-Christ vous sera pleinement accordée.", reference: "2 Pierre 1:11", theme: "Grâce" },
  { text: "Car l'Éternel Dieu est un soleil et un bouclier, l'Éternel donne la grâce et la gloire, il ne refuse aucun bien à ceux qui marchent dans l'intégrité.", reference: "Psaumes 84:12", theme: "Grâce" },
  { text: "Éternel des armées ! Heureux l'homme qui se confie en toi !", reference: "Psaumes 84:13", theme: "Grâce" },
  { text: "Je rends grâces à mon Dieu de tout le souvenir que je garde de vous.", reference: "Philippiens 1:3", theme: "Grâce" },
  { text: "Je suis persuadé que celui qui a commencé en vous cette bonne œuvre la rendra parfaite pour le jour de Jésus-Christ.", reference: "Philippiens 1:6", theme: "Grâce" },
  { text: "Et ce que je demande dans mes prières, c'est que votre amour augmente de plus en plus en connaissance et en toute intelligence.", reference: "Philippiens 1:9", theme: "Grâce" },
  { text: "Pour le discernement des choses les meilleures, afin que vous soyez purs et irréprochables pour le jour de Christ.", reference: "Philippiens 1:10", theme: "Grâce" },
  { text: "Remplis du fruit de justice qui est par Jésus-Christ, à la gloire et à la louange de Dieu.", reference: "Philippiens 1:11", theme: "Grâce" },
  { text: "Béni soit Dieu, le Père de notre Seigneur Jésus-Christ, qui nous a bénis de toutes sortes de bénédictions spirituelles dans les lieux célestes en Christ !", reference: "Éphésiens 1:3", theme: "Grâce" },
  { text: "En lui Dieu nous a élus avant la fondation du monde, pour que nous soyons saints et irréprochables devant lui.", reference: "Éphésiens 1:4", theme: "Grâce" },
  { text: "Nous ayant prédestinés dans son amour à être ses enfants d'adoption par Jésus-Christ, selon le bon plaisir de sa volonté.", reference: "Éphésiens 1:5", theme: "Grâce" },
  { text: "À la louange de la gloire de sa grâce, qu'il nous a accordée en son Bien-aimé.", reference: "Éphésiens 1:6", theme: "Grâce" },
  { text: "En lui nous avons la rédemption par son sang, la rémission des péchés, selon la richesse de sa grâce.", reference: "Éphésiens 1:7", theme: "Grâce" },
  { text: "Que la grâce de notre Seigneur Jésus-Christ soit avec vous tous !", reference: "2 Thessaloniciens 3:18", theme: "Grâce" },

  // 401-450 : Prière et Exaucement
  { text: "Demandez, et l'on vous donnera ; cherchez, et vous trouverez ; frappez, et l'on vous ouvrira.", reference: "Matthieu 7:7", theme: "Prière" },
  { text: "Car quiconque demande reçoit, celui qui cherche trouve, et l'on ouvre à celui qui frappe.", reference: "Matthieu 7:8", theme: "Prière" },
  { text: "Tout ce que vous demanderez avec foi par la prière, vous le recevrez.", reference: "Matthieu 21:22", theme: "Prière" },
  { text: "C'est pourquoi je vous dis : Tout ce que vous demanderez en priant, croyez que vous l'avez reçu, et vous le verrez s'accomplir.", reference: "Marc 11:24", theme: "Prière" },
  { text: "Et si vous demeurez en moi, et que mes paroles demeurent en vous, demandez ce que vous voudrez, et cela vous sera accordé.", reference: "Jean 15:7", theme: "Prière" },
  { text: "Ne vous inquiétez de rien ; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces.", reference: "Philippiens 4:6", theme: "Prière" },
  { text: "Persévérez dans la prière, veillez-y avec actions de grâces.", reference: "Colossiens 4:2", theme: "Prière" },
  { text: "Priez sans cesse.", reference: "1 Thessaloniciens 5:17", theme: "Prière" },
  { text: "La prière fervente du juste a une grande efficacité.", reference: "Jacques 5:16", theme: "Prière" },
  { text: "Confessez donc vos péchés les uns aux autres, et priez les uns pour les autres, afin que vous soyez guéris.", reference: "Jacques 5:16", theme: "Prière" },
  { text: "Si nous confessons nos péchés, il est fidèle et juste pour nous les pardonner, et pour nous purifier de toute iniquité.", reference: "1 Jean 1:9", theme: "Prière" },
  { text: "Nous avons auprès de lui cette assurance, que si nous demandons quelque chose selon sa volonté, il nous écoute.", reference: "1 Jean 5:14", theme: "Prière" },
  { text: "Et si nous savons qu'il nous écoute, quelque chose que nous demandions, nous savons que nous possédons la chose que nous lui avons demandée.", reference: "1 Jean 5:15", theme: "Prière" },
  { text: "Éternel ! écoute ma prière, et prête l'oreille à mes supplications ! Exauce-moi dans tu fidélité, dans ta justice !", reference: "Psaumes 143:1", theme: "Prière" },
  { text: "Je t'invoque au jour de ma détresse, car tu m'exauces.", reference: "Psaumes 86:7", theme: "Prière" },
  { text: "Invoque-moi, et je te répondrai ; je t'annoncerai de grandes choses, des choses cachées, que tu ne connais pas.", reference: "Jérémie 33:3", theme: "Prière" },
  { text: "Quand un malheureux crie, l'Éternel entend, et il le sauve de toutes ses détresses.", reference: "Psaumes 34:7", theme: "Prière" },
  { text: "Les yeux de l'Éternel sont sur les justes, et ses oreilles sont attentives à leurs cris.", reference: "Psaumes 34:16", theme: "Prière" },
  { text: "Quand les justes crient, l'Éternel entend, et il les délivre de toutes leurs détresses.", reference: "Psaumes 34:18", theme: "Prière" },
  { text: "L'Éternel est près de tous ceux qui l'invoquent, de tous ceux qui l'invoquent avec sincérité.", reference: "Psaumes 145:18", theme: "Prière" },
  { text: "Il accomplit les désirs de ceux qui le craignent, il entend leur cri et il les sauve.", reference: "Psaumes 145:19", theme: "Prière" },
  { text: "Avant qu'ils m'invoquent, je répondrai ; avant qu'ils aient cessé de parler, j'aurai exaucé.", reference: "Ésaïe 65:24", theme: "Prière" },
  { text: "Vous m'invoquerez, et vous partirez ; vous me prierez, et je vous exaucerai.", reference: "Jérémie 29:12", theme: "Prière" },
  { text: "Vous me chercherez, et vous me trouverez, si vous me cherchez de tout votre cœur.", reference: "Jérémie 29:13", theme: "Prière" },
  { text: "Je me laisserai trouver par vous, dit l'Éternel.", reference: "Jérémie 29:14", theme: "Prière" },
  { text: "Éternel ! le matin tu entends ma voix ; le matin je me tourne vers toi, et j'attends.", reference: "Psaumes 5:4", theme: "Prière" },
  { text: "Mais moi, je t'invoque, ô Éternel ! Et le matin ma prière va au-devant de toi.", reference: "Psaumes 88:14", theme: "Prière" },
  { text: "Dès le matin, fais-moi entendre ta bonté ! Car je me confie en toi. Fais-moi connaître le chemin où je dois marcher !", reference: "Psaumes 143:8", theme: "Prière" },
  { text: "Délivre-moi de mes ennemis, ô Éternel ! Auprès de toi je cherche un refuge.", reference: "Psaumes 143:9", theme: "Prière" },
  { text: "Enseigne-moi à faire ta volonté ! Car tu es mon Dieu. Que ton bon esprit me conduise sur la voie droite !", reference: "Psaumes 143:10", theme: "Prière" },
  { text: "À cause de ton nom, Éternel ! rends-moi la vie ; dans ta justice, retire mon âme de la détresse !", reference: "Psaumes 143:11", theme: "Prière" },
  { text: "J'aime l'Éternel, car il entend ma voix, mes supplications.", reference: "Psaumes 116:1", theme: "Prière" },
  { text: "Car il a penché son oreille vers moi ; et je l'invoquerai toute ma vie.", reference: "Psaumes 116:2", theme: "Prière" },
  { text: "J'avais invoqué le nom de l'Éternel : Ô Éternel, sauve mon âme !", reference: "Psaumes 116:4", theme: "Prière" },
  { text: "L'Éternel est indulgent et juste, notre Dieu est plein de compassion.", reference: "Psaumes 116:5", theme: "Prière" },
  { text: "L'Éternel garde les simples ; j'étais malheureux, et il m'a sauvé.", reference: "Psaumes 116:6", theme: "Prière" },
  { text: "Retourne, mon âme, à ton repos, car l'Éternel t'a fait du bien.", reference: "Psaumes 116:7", theme: "Prière" },
  { text: "Oui, tu as délivré mon âme de la mort, mes yeux des larmes, mes pieds de la chute.", reference: "Psaumes 116:8", theme: "Prière" },
  { text: "Je marcherai devant l'Éternel, sur la terre des vivants.", reference: "Psaumes 116:9", theme: "Prière" },
  { text: "Comment rendrai-je à l'Éternel tous ses bienfaits envers moi ?", reference: "Psaumes 116:12", theme: "Prière" },
  { text: "J'élèverai la coupe du salut, et j'invoquerai le nom de l'Éternel.", reference: "Psaumes 116:13", theme: "Prière" },
  { text: "Je t'offrirai un sacrifice d'action de grâces, et j'invoquerai le nom de l'Éternel.", reference: "Psaumes 116:17", theme: "Prière" },
  { text: "Louez l'Éternel, vous toutes les nations, célébrez-le, vous tous les peuples !", reference: "Psaumes 117:1", theme: "Prière" },
  { text: "Car sa bonté pour nous est grande, et sa fidélité dure à toujours. Louez l'Éternel !", reference: "Psaumes 117:2", theme: "Prière" },
  { text: "Rendez grâces à l'Éternel, car il est bon, car sa miséricorde dure à toujours !", reference: "Psaumes 118:1", theme: "Prière" },
  { text: "Du sein de la détresse j'ai invoqué l'Éternel : l'Éternel m'a exaucé, m'a mis au large.", reference: "Psaumes 118:5", theme: "Prière" },
  { text: "L'Éternel est pour moi, je ne crains rien : Que peuvent me faire des hommes ?", reference: "Psaumes 118:6", theme: "Prière" },
  { text: "Mieux vaut chercher un refuge en l'Éternel que de se confier à l'homme.", reference: "Psaumes 118:8", theme: "Prière" },
  { text: "Mieux vaut chercher un refuge en l'Éternel que de se confier aux grands.", reference: "Psaumes 118:9", theme: "Prière" },
  { text: "Ma force et le sujet de mes chants, c'est l'Éternel ; il m'a sauvé.", reference: "Psaumes 118:14", theme: "Prière" },

  // 451-500 : Guidance, Protection et Bénédiction
  { text: "Ta parole est une lampe à mes pieds, et une lumière sur mon sentier.", reference: "Psaumes 119:105", theme: "Guidance" },
  { text: "L'Éternel te gardera de tout mal, il gardera ton âme.", reference: "Psaumes 121:7", theme: "Guidance" },
  { text: "L'Éternel gardera ton départ et ton arrivée, dès maintenant et à jamais.", reference: "Psaumes 121:8", theme: "Guidance" },
  { text: "Reconnais-le dans toutes tes voies, et il aplanira tes sentiers.", reference: "Proverbes 3:6", theme: "Guidance" },
  { text: "L'Éternel sera toujours ton guide, il rassasiera ton âme dans les lieux arides.", reference: "Ésaïe 58:11", theme: "Guidance" },
  { text: "Le cœur de l'homme médite sa voie, mais c'est l'Éternel qui dirige ses pas.", reference: "Proverbes 16:9", theme: "Guidance" },
  { text: "Il y a beaucoup de projets dans le cœur de l'homme, mais c'est le dessein de l'Éternel qui s'accomplit.", reference: "Proverbes 19:21", theme: "Guidance" },
  { text: "Dirige mes pas dans ta parole, et ne laisse aucune iniquité dominer sur moi !", reference: "Psaumes 119:133", theme: "Guidance" },
  { text: "Fais-moi connaître tes voies, ô Éternel ! Enseigne-moi tes sentiers !", reference: "Psaumes 25:4", theme: "Guidance" },
  { text: "Conduis-moi dans ta vérité, et instruis-moi ; car tu es le Dieu de mon salut, tu es ma force toujours.", reference: "Psaumes 25:5", theme: "Guidance" },
  { text: "L'Éternel est bon et droit : c'est pourquoi il montre aux pécheurs la voie à suivre.", reference: "Psaumes 25:8", theme: "Guidance" },
  { text: "Il conduit les humbles dans la justice, il enseigne aux humbles sa voie.", reference: "Psaumes 25:9", theme: "Guidance" },
  { text: "Tous les sentiers de l'Éternel sont miséricorde et fidélité, pour ceux qui gardent son alliance.", reference: "Psaumes 25:10", theme: "Guidance" },
  { text: "Quel est l'homme qui craint l'Éternel ? L'Éternel lui montre la voie qu'il doit choisir.", reference: "Psaumes 25:12", theme: "Guidance" },
  { text: "Son âme reposera dans le bonheur, et sa postérité possédera le pays.", reference: "Psaumes 25:13", theme: "Guidance" },
  { text: "L'amitié de l'Éternel est pour ceux qui le craignent, et son alliance leur donne instruction.", reference: "Psaumes 25:14", theme: "Guidance" },
  { text: "Mes yeux sont constamment tournés vers l'Éternel, car c'est lui qui fera sortir mes pieds du filet.", reference: "Psaumes 25:15", theme: "Guidance" },
  { text: "Tourne-toi vers moi et aie pitié de moi, car je suis abandonné et malheureux.", reference: "Psaumes 25:16", theme: "Guidance" },
  { text: "Les angoisses de mon cœur augmentent ; tire-moi de mes détresses !", reference: "Psaumes 25:17", theme: "Guidance" },
  { text: "Vois ma misère et ma peine, et pardonne tous mes péchés.", reference: "Psaumes 25:18", theme: "Guidance" },
  { text: "Garde mon âme et sauve-moi ! Que je ne sois pas confus, quand je cherche en toi mon refuge.", reference: "Psaumes 25:20", theme: "Guidance" },
  { text: "Que l'intégrité et la droiture me protègent, quand je mets en toi mon espérance !", reference: "Psaumes 25:21", theme: "Guidance" },
  { text: "Rends-moi la joie de ton salut, et qu'un esprit de bonne volonté me soutienne !", reference: "Psaumes 51:14", theme: "Guidance" },
  { text: "Je t'instruirai et te montrerai la voie que tu dois suivre ; je te conseillerai, j'aurai le regard sur toi.", reference: "Psaumes 32:8", theme: "Guidance" },
  { text: "Ne soyez pas comme un cheval ou un mulet sans intelligence.", reference: "Psaumes 32:9", theme: "Guidance" },
  { text: "Beaucoup de douleurs sont la part du méchant, mais celui qui se confie en l'Éternel est environné de sa grâce.", reference: "Psaumes 32:10", theme: "Guidance" },
  { text: "Justes, réjouissez-vous en l'Éternel et soyez dans l'allégresse ! Poussez des cris de joie, vous tous qui avez le cœur droit !", reference: "Psaumes 32:11", theme: "Guidance" },
  { text: "L'Éternel garde les étrangers, il soutient l'orphelin et la veuve.", reference: "Psaumes 146:9", theme: "Guidance" },
  { text: "Il guérit ceux qui ont le cœur brisé, et panse leurs blessures.", reference: "Psaumes 147:3", theme: "Guidance" },
  { text: "Il prépare la pluie pour la terre ; il fait germer l'herbe sur les montagnes.", reference: "Psaumes 147:8", theme: "Guidance" },
  { text: "Le Seigneur prend plaisir en ceux qui le craignent, en ceux qui espèrent en sa bonté.", reference: "Psaumes 147:11", theme: "Guidance" },
  { text: "Célèbre l'Éternel, ô Jérusalem ! Loue ton Dieu, ô Sion !", reference: "Psaumes 147:12", theme: "Guidance" },
  { text: "Car il affermit les barres de tes portes, il bénit tes fils au milieu de toi.", reference: "Psaumes 147:13", theme: "Guidance" },
  { text: "Il rend la paix à ton territoire, il te rassasie du meilleur froment.", reference: "Psaumes 147:14", theme: "Guidance" },
  { text: "Il envoie ses ordres sur la terre : sa parole court avec rapidité.", reference: "Psaumes 147:15", theme: "Guidance" },
  { text: "Il révèle sa parole à Jacob, ses lois et ses ordonnances à Israël.", reference: "Psaumes 147:19", theme: "Guidance" },
  { text: "L'Éternel est ton gardien, l'Éternel est ton ombre à ta main droite.", reference: "Psaumes 121:5", theme: "Guidance" },
  { text: "Pendant le jour le soleil ne te frappera point, ni la lune pendant la nuit.", reference: "Psaumes 121:6", theme: "Guidance" },
  { text: "Le sentier des justes est comme la lumière resplendissante, dont l'éclat va croissant jusqu'au milieu du jour.", reference: "Proverbes 4:18", theme: "Guidance" },
  { text: "La voie des méchants est comme les ténèbres ; ils ne s'aperçoivent pas de ce qui les fera tomber.", reference: "Proverbes 4:19", theme: "Guidance" },
  { text: "Mon fils, sois attentif à mes paroles, prête l'oreille à mes discours.", reference: "Proverbes 4:20", theme: "Guidance" },
  { text: "Qu'ils ne s'éloignent pas de tes yeux ; garde-les dans le fond de ton cœur.", reference: "Proverbes 4:21", theme: "Guidance" },
  { text: "Car c'est la vie pour ceux qui les trouvent, et la santé pour tout leur corps.", reference: "Proverbes 4:22", theme: "Guidance" },
  { text: "Garde ton cœur plus que toute autre chose, car de lui viennent les sources de la vie.", reference: "Proverbes 4:23", theme: "Guidance" },
  { text: "Écarte de ta bouche la fausseté, éloigne de tes lèvres les détours.", reference: "Proverbes 4:24", theme: "Guidance" },
  { text: "Que tes yeux regardent en face, et que tes paupières se dirigent devant toi.", reference: "Proverbes 4:25", theme: "Guidance" },
  { text: "Considère le chemin par où tu marches, et que toutes tes voies soient bien réglées.", reference: "Proverbes 4:26", theme: "Guidance" },
  { text: "Ne t'incline ni à droite ni à gauche, et détourne ton pied du mal.", reference: "Proverbes 4:27", theme: "Guidance" },
  { text: "L'Éternel est mon rocher, ma forteresse, mon libérateur ! Mon Dieu, mon rocher, où je trouve un abri !", reference: "Psaumes 18:3", theme: "Guidance" },
  { text: "Que la grâce du Seigneur Jésus-Christ soit avec vous tous ! Amen !", reference: "Philippiens 4:23", theme: "Guidance" }
];

export function getDailyVerse(): Verse {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime() + (start.getTimezoneOffset() - now.getTimezoneOffset()) * 60 * 1000;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  const index = dayOfYear % verses.length;
  return verses[index];
}

export function getVerseContext(verseRef: string) {
  const index = verses.findIndex((v) => v.reference === verseRef);
  if (index === -1) {
    return { before: [], after: [] };
  }
  
  const before: Verse[] = [];
  for (let i = 2; i >= 1; i--) {
    const idx = index - i;
    if (idx >= 0) {
      before.push(verses[idx]);
    }
  }
  
  const after: Verse[] = [];
  for (let i = 1; i <= 2; i++) {
    const idx = index + i;
    if (idx < verses.length) {
      after.push(verses[idx]);
    }
  }
  
  return { before, after };
}
