import { NextResponse } from "next/server";

const BIBLE_BOOKS = [
  { name: "Genèse", chapters: 50 },
  { name: "Exode", chapters: 40 },
  { name: "Lévitique", chapters: 27 },
  { name: "Nombres", chapters: 36 },
  { name: "Deutéronome", chapters: 34 },
  { name: "Josué", chapters: 24 },
  { name: "Juges", chapters: 21 },
  { name: "Ruth", chapters: 4 },
  { name: "1 Samuel", chapters: 31 },
  { name: "2 Samuel", chapters: 24 },
  { name: "1 Rois", chapters: 22 },
  { name: "2 Rois", chapters: 25 },
  { name: "1 Chroniques", chapters: 29 },
  { name: "2 Chroniques", chapters: 36 },
  { name: "Esdras", chapters: 10 },
  { name: "Néhémie", chapters: 13 },
  { name: "Esther", chapters: 10 },
  { name: "Job", chapters: 42 },
  { name: "Psaumes", chapters: 150 },
  { name: "Proverbes", chapters: 31 },
  { name: "Ecclésiaste", chapters: 12 },
  { name: "Cantique des Cantiques", chapters: 8 },
  { name: "Ésaïe", chapters: 66 },
  { name: "Jérémie", chapters: 52 },
  { name: "Lamentations", chapters: 5 },
  { name: "Ézéchiel", chapters: 48 },
  { name: "Daniel", chapters: 12 },
  { name: "Osée", chapters: 14 },
  { name: "Joël", chapters: 3 },
  { name: "Amos", chapters: 9 },
  { name: "Abdias", chapters: 1 },
  { name: "Jonas", chapters: 4 },
  { name: "Michée", chapters: 7 },
  { name: "Nahum", chapters: 3 },
  { name: "Habacuc", chapters: 3 },
  { name: "Sophonie", chapters: 3 },
  { name: "Aggée", chapters: 2 },
  { name: "Zacharie", chapters: 14 },
  { name: "Malachie", chapters: 4 },
  { name: "Matthieu", chapters: 28 },
  { name: "Marc", chapters: 16 },
  { name: "Luc", chapters: 24 },
  { name: "Jean", chapters: 21 },
  { name: "Actes", chapters: 28 },
  { name: "Romains", chapters: 16 },
  { name: "1 Corinthiens", chapters: 16 },
  { name: "2 Corinthiens", chapters: 13 },
  { name: "Galates", chapters: 6 },
  { name: "Éphésiens", chapters: 6 },
  { name: "Philippiens", chapters: 4 },
  { name: "Colossiens", chapters: 4 },
  { name: "1 Thessaloniciens", chapters: 5 },
  { name: "2 Thessaloniciens", chapters: 3 },
  { name: "1 Timothée", chapters: 6 },
  { name: "2 Timothée", chapters: 4 },
  { name: "Tite", chapters: 3 },
  { name: "Philémon", chapters: 1 },
  { name: "Hébreux", chapters: 13 },
  { name: "Jacques", chapters: 5 },
  { name: "1 Pierre", chapters: 5 },
  { name: "2 Pierre", chapters: 3 },
  { name: "1 Jean", chapters: 5 },
  { name: "2 Jean", chapters: 1 },
  { name: "3 Jean", chapters: 1 },
  { name: "Jude", chapters: 1 },
  { name: "Apocalypse", chapters: 22 }
];

export async function GET() {
  return new NextResponse(JSON.stringify(BIBLE_BOOKS), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600" // Cache de 1 heure
    }
  });
}
